server:
  port: 8080
spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:mysql://localhost:3306/accounts_bank_aht
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
