version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Huynguyen11102002

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  transaction-service:
    image: huy696980/transaction-service:1.0
    container_name: transaction-service
    restart: always
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/transaction-service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Huynguyen11102002
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - mariadb_data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
